name: run_test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: submodule init
      run: git submodule update --init --recursive
    - name: mkdir build
      run: mkdir build
    - name: cmake
      working-directory: ./build
      run: cmake ..
    - name: make
      working-directory: ./build
      run: make
    - name: run test
      run: ./build/test/all_tests
